musicers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :users, only: [:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :musics, only: [:new, :create, :index, :show, :destroy, :edit,:update] do
    resource :favorites ,only:[:create,:destroy]
    resources :music_comments, only:[:new,:create,:edit,:destroy,:update]
  end
  get 'index_date' => 'musics#index_new_date', as: 'index_new_date'
  get 'index_desc' => 'musics#index_rate_desc', as: 'index_rate_desc'
  get 'search_genre'=> 'musics#search_genre', as: 'search_genre'

  resources :groups ,only:[:new,:create,:edit,:update,:show,:index,:destroy] do
    resources :group_users,only:[:create,:destroy,:index]
  end

  get 'chat/:id' => 'chats#show',as: 'chat'
  resources :chats, only:[:create]

  get 'home' => 'musics#home', as: 'home'

  get 'search' => 'musics#search', as: 'search'

end

musicers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

musicers/app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

musicers/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :music
end

musicers/app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users ,through: :group_users
  validates :name, presence: true ,uniqueness: true

  attachment :image
  
  def joined_by?(user)
    group_users.where(user_id: user.id).exists?
  end
  
  
  
end

musicers/app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user


end

musicers/app/models/music.rb
class Music < ApplicationRecord

    attachment :musicimage
    belongs_to :user
    has_many :music_comments ,dependent: :destroy
    has_many :favorites ,dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    
    def self.search(keyword)
      where(["music_name like? OR music_genre like?","%#{keyword}%","%#{keyword}%" ])
    end
    

end

musicers/app/models/music_comment.rb
class MusicComment < ApplicationRecord

  belongs_to :user
  belongs_to :music
end

musicers/app/models/relationship.rb
class Relationship < ApplicationRecord

belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

musicers/app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

musicers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reverse_of_relationships, class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followers, through: :reverse_of_relationships ,source: :follower

  has_many :relationships, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :followings ,through: :relationships, source: :followed


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def followed?(user)
    followers.include?(user)
  end

  attachment :profile_image
  has_many :musics, dependent: :destroy
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

musicers/app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

musicers/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end


  def create
    @chat = current_user.chats.new(chat_params)
    @room = @chat.room_id
    @chat_n = Chat.new(room_id: @room)
    @chats = Chat.where(room_id: @room)
   @chat.save
  end


  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

musicers/app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController

  def create
    @group = Group.find(params[:group_id])
    @group_user = GroupUser.new(group_id: @group.id)
    @group_user.user_id = current_user.id
    @group_user.save
    redirect_to group_path(@group)
  end

  def destroy
    @group = Group.find(params[:group_id])
    @group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id)
    @group_user.destroy
    redirect_to group_path(@group)
  end


  def index
    @group = Group.find(params[:group_id])
    @group_users = @group.group_users
  end

end

musicers/app/controllers/homes_controller.rb
class HomesController < ApplicationController

    def top
        @musics = Music.all
    end

end

musicers/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @musics = @user.musics.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)

  end


end

musicers/app/helpers/application_helper.rb
module ApplicationHelper
end

musicers/app/helpers/chats_helper.rb
module ChatsHelper
end

musicers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

musicers/app/helpers/group_users_helper.rb
module GroupUsersHelper
end

musicers/app/helpers/groups_helper.rb
module GroupsHelper
end

musicers/app/helpers/homes_helper.rb
module HomesHelper
end

musicers/app/helpers/musics_helper.rb
module MusicsHelper
end

musicers/app/helpers/users_helper.rb
module UsersHelper
end

musicers/app/views/group_users/index.html.erb
<div class="container" style="height:1000px;">
  <h1 class="text-center my-5">Group Member</h1>
  <div class="row">
    <div class="col-8 mx-auto">
    <% if @group_users.exists?  %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th>Follow</th>
            <th>Chat</th>
          </tr>
        </thead>
        <tbody>
          <% @group_users.each do |group_user|  %>
          <tr>
            <td class="align-middle"><%= link_to user_path(group_user.user_id) do %><%= attachment_image_tag group_user.user, :profile_image, size: "50x50", fallback: "no_image.jpg",class: "mt-3 rounded-circle"  %><% end %></td>
            <td class="align-middle"><%= link_to user_path(group_user.user_id),class: "text-info" do %><%= group_user.user.name %><% end %></td>
            <td class="align-middle">
            <% unless current_user.id == group_user.user_id %>
              <% if current_user.followings.exists?(group_user.user_id) %>
                <%= link_to user_relationships_path(group_user.user_id), method: :delete ,class: "text-info" do %><i class="fas fa-user-slash">&nbsp;Unfollow</i><% end %>
              <% else %>
                <%= link_to user_relationships_path(group_user.user_id), method: :post,class: "text-info"   do %><i class="fas fa-user-check">&nbsp;Follow</i><% end %>
              <% end %>
            <% end %>
            </td>
            <td class="align-middle">
              <% if (current_user.followings.exists? group_user.user_id)  && (group_user.user.followings.exists? current_user.id )%>
                <%= link_to chat_path(group_user.user_id) do  %>
                <div class="btn btn-info"><i class="far fa-envelope">Chat</i></div>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h1 class="text-center mt-5 "><i class="fas fa-users-slash">No Member</i></h1>
    <% end %>
    </div>
  </div>
</div>