musicers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :users, only: [:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :musics, only: [:new, :create, :index, :show, :destroy, :edit,:update] do
    resource :favorites ,only:[:create,:destroy]
    resources :music_comments, only:[:new,:create,:edit,:destroy,:update]
  end
  get 'index_date' => 'musics#index_new_date', as: 'index_new_date'
  get 'index_desc' => 'musics#index_rate_desc', as: 'index_rate_desc'
  get 'search_genre'=> 'musics#search_genre', as: 'search_genre'

  resources :groups ,only:[:new,:create,:edit,:update,:show,:index,:destroy] do
    resources :group_users,only:[:create,:destroy,:index]
  end

  get 'chat/:id' => 'chats#show',as: 'chat'
  resources :chats, only:[:create]

  get 'home' => 'musics#home', as: 'home'

  get 'search' => 'musics#search', as: 'search'

end

musicers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

musicers/app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

musicers/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :music
end

musicers/app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users ,through: :group_users
  validates :name, presence: true ,uniqueness: true

  attachment :image
  
  def joined_by?(user)
    group_users.where(user_id: user.id).exists?
  end
  
  
  
end

musicers/app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user


end

musicers/app/models/music.rb
class Music < ApplicationRecord

    attachment :musicimage
    belongs_to :user
    has_many :music_comments ,dependent: :destroy
    has_many :favorites ,dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    
    def self.search(keyword)
      where(["music_name like? OR music_genre like?","%#{keyword}%","%#{keyword}%" ])
    end
    

end

musicers/app/models/music_comment.rb
class MusicComment < ApplicationRecord

  belongs_to :user
  belongs_to :music
end

musicers/app/models/relationship.rb
class Relationship < ApplicationRecord

belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

musicers/app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

musicers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reverse_of_relationships, class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followers, through: :reverse_of_relationships ,source: :follower

  has_many :relationships, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :followings ,through: :relationships, source: :followed


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def followed?(user)
    followers.include?(user)
  end

  attachment :profile_image
  has_many :musics, dependent: :destroy
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

musicers/app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

musicers/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end


  def create
    @chat = current_user.chats.new(chat_params)
    @room = @chat.room_id
    @chat_n = Chat.new(room_id: @room)
    @chats = Chat.where(room_id: @room)
   @chat.save
  end


  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

musicers/app/helpers/application_helper.rb
module ApplicationHelper
end

musicers/app/helpers/chats_helper.rb
module ChatsHelper
end

musicers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

musicers/app/helpers/group_users_helper.rb
module GroupUsersHelper
end

musicers/app/helpers/groups_helper.rb
module GroupsHelper
end

musicers/app/helpers/homes_helper.rb
module HomesHelper
end

musicers/app/helpers/musics_helper.rb
module MusicsHelper
end

musicers/app/helpers/users_helper.rb
module UsersHelper
end

musicers/app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicers</title>
    <%= csrf_meta_tags %>
    <script src="https://kit.fontawesome.com/fe634eb8bd.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" >
  </head>

 <body　class="d-flex flex-column vh-100">
  <header class="shadow-lg">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#e3f2fd;">
      <div class="container">
        <a class="navbar-brand mr-auto" href="/"><i class="fas fa-headphones-alt">Musicers</i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-dark' do %><i class="fas fa-sign-out-alt">Logout</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_path,class: 'nav-link text-dark' do %><i class="fas fa-house-user">Home</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user),class: 'nav-link text-dark' do %><i class="fas fa-user">Mypage</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_music_path,class: 'nav-link text-dark' do %><i class="fas fa-plus">NewPost</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to musics_path,class: 'nav-link text-dark' do %><i class="fas fa-headphones-alt">Musics</i><% end %>
            </li>

            <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %><i class="fas fa-user-plus">SignUp</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path,class: 'nav-link text-dark' do %><i class="fas fa-sign-in-alt">Login</i><% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>


  <%= yield %>


<footer class="footer mt-5" >
  <a class="mr-4 mb-5" href="#" id="page-top">TOP</a>
  <div class="row mb-2 pt-2" style="background-color:#e3f2fd; height: 40px">
    <div class="mx-auto">
      <i>Copyright © 2013 Apple Inc. All rights reserved.</i>
    </div>
  </div>

</footer>

</body>

musicers/app/views/layouts/_chat.html.erb
<div class="col-6 offset-3">
      <% if chats.present?  %>
        <% chats.each do |chat| %>
          <% if chat.user_id == current_user.id  %>
            <div class="speech-bubble mt-3">
              <div class="sb-bubble sb-line1 sb-right mt-2">
                <strong><%= chat.message %></strong>
              </div>
            </div>
          <% else %>
            <div>
              <%= link_to user_path(chat.user) do %>
                <%= attachment_image_tag chat.user,:profile_image,:fill,40,40, fallback: "no_image.jpg",size: '40x40' ,class: "user-image" %>
              <% end %>
            </div>
            <div class="speech-bubble mt-3">
              <div class="sb-bubble sb-line1 sb-left mt-2">
                <strong><%= chat.message %></strong>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>

      <div class="posts mb-4" style="margin-top:300px;">
      <div style="width:400px;">
        <%= form_with model: chat, local: false do |f| %>
        <%= f.text_field :message, placeholder: "Message", class: "form-inline form-control", size:"30" %>
        <%= f.hidden_field :room_id  %>
      </div>
      <button class=" btn btn-info btn-sm " sryle="width: 100px;"><i class="fab fa-telegram-plane">Send<%f.submit %></i></button>
        <% end %>
    </div>
    </div>

musicers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicers</title>
    <%= csrf_meta_tags %>
    <script src="https://kit.fontawesome.com/fe634eb8bd.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" >
  </head>

 <body　class="d-flex flex-column vh-100">
 <div id="all">
  <header id="header" class="shadow-lg sticky-top" >
    <nav class="navbar navbar-expand navbar-light" style="background-color:#e3f2fd; height:65px;">
      <div class="container">
        <a class="navbar-brand mr-auto" href="/"><i class="fas fa-headphones-alt">Musicers</i></a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-dark' do %><i class="fas fa-sign-out-alt">Logout</i><% end %>
            </li>
            <li class="nav-item" >
              <%= link_to "#",class: 'nav-link text-dark',id: "search" do %><i class="fas fa-search-plus">Search</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_path,class: 'nav-link text-dark' do %><i class="fas fa-house-user">Home</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user),class: 'nav-link text-dark' do %><i class="fas fa-user">Mypage</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_music_path,class: 'nav-link text-dark' do %><i class="fas fa-plus">NewPost</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to musics_path,class: 'nav-link text-dark' do %><i class="fas fa-headphones-alt">Musics</i><% end %>
            </li>
            <li class="nav-item" >
              <%= link_to groups_path ,class: 'nav-link text-dark',id: "search" do %><i class="fas fa-users">Groups</i><% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %><i class="fas fa-user-plus">SignUp</i><% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path,class: 'nav-link text-dark' do %><i class="fas fa-sign-in-alt">Login</i><% end %>
            </li>
            <% end %>
          </ul>
        </div>
        <div id="hm-icon">
          <a class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <div class=" py-5 " id="search-form" >
      <div class="search-box">
        <div class="d-inline">
          <%= form_with url: search_path, method: :get,  local: true do |f|%>
            <%= f.text_field :keyword, value: @keyword ,placeholder: "Search",class: "form-control " ,id: "form-control"%>
        </div>
        <button class="btn">
          <i class="fas fa-search fa-lg "></i>
          <% f.submit %>
        </button>
          <% end %>
      </div>
    </div>
    <div id="sp-menu" class="pt-5">
      <ul class="hidden-menu ml-auto " style="list-style-type: none" >
        <% if user_signed_in? %>
        <li class="menu-item">
          <%= link_to home_path,class: 'nav-link text-dark' do %><i class="fas fa-house-user">Home</i><% end %>
        </li>
        <li class="menu-item">
          <%= link_to user_path(current_user),class: 'nav-link text-dark' do %><i class="fas fa-user">Mypage</i><% end %>
        </li>
        <li class="menu-item">
          <%= link_to new_music_path,class: 'nav-link text-dark' do %><i class="fas fa-plus">NewPost</i><% end %>
        </li>
        <li class="menu-item">
          <%= link_to musics_path,class: 'nav-link text-dark' do %><i class="fas fa-headphones-alt">Musics</i><% end %>
        </li>
        <li class="nav-item" >
          <%= link_to groups_path ,class: 'nav-link text-dark',id: "search" do %><i class="fas fa-users">Groups</i><% end %>
        </li>
        <li class="nav-item" >
          <%= link_to "#",class: 'nav-link text-dark',id: "search" do %><i class="fas fa-search-plus">Search</i><% end %>
        </li>
        <li class="menu-item">
          <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-dark' do %><i class="fas fa-sign-out-alt">Logout</i><% end %>
        </li>
        <% else %>
        <li class="menu-item">
          <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %><i class="fas fa-user-plus">SignUp</i><% end %>
        </li>
        <li class="menu-item">
          <%= link_to new_user_session_path,class: 'nav-link text-dark' do %><i class="fas fa-sign-in-alt">Login</i><% end %>
        </li>
        <% end %>
      </ul>
    </div>

      <%= yield %>

  </main>

   <footer id="footer">
    <a class="mr-4 mb-5" href="#" id="page-top">TOP</a>
    <div class="row mb-2 pt-2" style="background-color:#e3f2fd; height: 40px">
      <div class="mx-auto">
        <i>Copyright © 2013 Apple Inc. All rights reserved.</i>
      </div>
    </div>
   </footer>
</div>
</body>